### PR TITLE
Get docker working again

### PR DESCRIPTION
**Pull request by geppy**
# Description 

Updates the Docker configurations, which have broken over time.

## More Details

- updates `Dockerfile` to use the `ruby:2.3` base image
- combines steps in the `Dockerfile` so the image has fewer layers
- installs managed dependencies outside of `/app`, which is likely to be mounted in dev environments
  - `.yarnrc` tells Yarn to install packages in `/node_modules` ([which will be found by Node's module loader](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders))
  - base `ruby:2.3` image tells Bundler to install gems in `/usr/local/bundle`
- adds `.dockerignore`, so unnecessary files aren't copied into the Docker image
- moves dev environment settings into `docker-compose.overrides.yml`
- adds back in `spec_helper.rb` settings that make Docker-based testing work
  - these settings were originally added in #332, but removed in 69e0c38

# Test Coverage

No coverage changes.

### CODE REVIEW

**Comment by geppy** [comment]
@julianguyen You're very welcome!

Do the wiki docs need updating?  [Installation](https://github.com/ifmeorg/ifme/wiki/Installation) could be reorganized, removing the Vagrant bits (since #887  was closed unmerged), and emphasizing that Docker users need to run `docker-compose exec app rake db:create` after `docker-compose up`.

**Comment by cpretzer** [comment]
Nice work on this @geppy!

**Comment by julianguyen** [comment]
@geppy Yeah let's update the docs :D Thanks so much for working on this! I'm sorry for the late response, been busy starting a new job.

**Comment by cpretzer** [comment]
I made an update to the docs here: https://github.com/ifmeorg/ifme/wiki/Installation

**Comment by julianguyen** [comment]
Thanks so much @cpretzer :D

**Pull request merged**
