### PR TITLE
[WIP] Start work on ProfileModal

### PR DESCRIPTION
**Pull request by LachlanRidley**
#786 New Profile Modal component

### CODE REVIEW

**Comment by nshki** [comment]
Hey @LachlanRidley! Thanks a bunch for working on this. Just wanted to check in and see where you were with progress. Would you like someone to own the task if you're too busy?

**Comment by aSquare14** [comment]
@LachlanRidley and @nshki  Can I work on this ?

**Comment by LachlanRidley** [comment]
@nshki, @aSquare14 sorry, yes, I've gotten too busy so please feel free to take it up :)

**Comment by aSquare14** [comment]
Thanks!

**Pull request closed without merging**
