### PR TITLE
Add confirmation mail while sign up

### PR DESCRIPTION
**Pull request by Revathyne**
# Description

Adding confirmation email when signing up
## More Details
Added confirmation token while signing up

## Corresponding Issue
https://github.com/ifmeorg/ifme/compare/main...Revathyne:issue_1955

Reviewing this pull request? Check out our [Code Review Practices](https://github.com/ifmeorg/ifme/wiki/Code-Review-Practices) guide if you haven't already!

### CODE REVIEW

**Review by julianguyen — APPROVED** [review]
Thanks for thinking of adding this! :)

**Comment by julianguyen** [comment]
Can you rebase this PR?

**Comment by Revathyne** [comment]
Hi,
 Thank you for approving my pull request. I will surely rebase this PR.

Thanks,
Revthy N E

**Comment by Revathyne** [comment]
Hi, I merged this pull request since I got the approval. Thank you.

**Pull request merged**
