### PR TITLE
Added Hyperlinks to FAQ pages

### PR DESCRIPTION
**Pull request by aSquare14**
# Description 

Issue #799 . Major work was done by  @f3mshep in PR #810 . I just rebased,resolved merge conflicts and will be adding Vietnamese support.
Apologies for opening a new PR , I did not know how to merge my commits in the old one as I was not collaborator.

## Corresponding Issue
#799 Added Hyperlinks in the FAQ section

### CODE REVIEW

**Comment by aSquare14** [comment]
@julianguyen  Why are the tests failing ? :O

**Comment by julianguyen** [comment]
Hmm looks like some kind of PSQL error, maybe the data didn't load properly. In this case, I'd just "rerun the workflow" in CircleCI. Maybe this warrants a fix in our Circle config. But it's unrelated to your changes! :) Great work

**Comment by aSquare14** [comment]
Yes, Sure

**Comment by aSquare14** [comment]
@julianguyen Tests went green ! Also, fixed the indent issue :100:

**Pull request merged**
