### PR TITLE
Fix userid security vulnerability

### PR DESCRIPTION
**Pull request by TimMoore**

### CODE REVIEW

**Comment by TimMoore** [comment]
The Circle CI failure is unrelated to this change, but I sent a fix in a separate pull request: https://github.com/ifmeorg/ifme/pull/813

Once that's merged, I'll rebase this one.

**Comment by julianguyen** [comment]
Ready to rebase!

**Comment by TimMoore** [comment]
Rebased 😄

**Comment by TimMoore** [comment]
Code Climate is complaining about a few things. I think none of them were actually introduced by this change, but are just in files that were changed in other places. I'll look at fixing them in another PR after this is merged.

**Comment by julianguyen** [comment]
Sounds good to me! Yeah looks like you can ignore those codeclimate issues! :)

**Pull request merged**
