### PR TITLE
Add missing de.yml translations to complete German i18n

### PR DESCRIPTION
**Pull request by marcelkalveram**
I've put together the German translations inside the `de.yml` file and fixed all the required configuration for the German language to work properly on the site.

Just wanted to give a heads-up, and that I'll be testing these in the next couple of days to make sure everything is really smooth.

### CODE REVIEW

**Comment by julianguyen** [comment]
Wow this is so awesome @marcelkalveram! Thank you so much for picking this up <3 Can you also email us at join.ifme@gmail.com so we can add you to our Slack? Thanks!

**Comment by marcelkalveram** [comment]
Added some more fixes. I think the most obvious mistakes are now eliminated. Next I need to go through those emails.

**Comment by sexybiggetje** [comment]
I left a few comments on Slack, I don't have a working dev env at hand. Most are minor changes.

**Comment by julianguyen** [comment]
Hey just checking on the status on this, can we finish this up? :)

**Comment by julianguyen** [comment]
Thanks so much, @marcelkalveram for wrapping this up! We're sorry we didn't get to review it and merge it right away. I'm going to merge this into `wrap-up-german-translations` and resolve the conflicts so we can finally merge this!

**Pull request closed without merging**
