### PR TITLE
Refactor top navigation

### PR DESCRIPTION
**Pull request by baohouse**
Addresses #595 

- [x] Make nav no longer push content below it (desktop)
- [x] Make nav no longer push content below it (mobile)
- [x] Fix display of secondary navigation when hovering over other primary nav links
- [x] Enhance some colors
- [x] Add CSS transition animation (desktop)
- [ ] Add CSS transition animation (mobile)
- [ ] Add missing Home link in mobile size
- [ ] Fix display of two active links in mobile size while on Categories or Moods pages.

### CODE REVIEW

**Comment by abrophy** [comment]
Tested locally, though the top-nav behavior has been addressed, some of the JS in that file that was dealing with the moments UI makes me want to hold off on merging it until we have the react version up, will review as soon as that's been taken care of

**Comment by baohouse** [comment]
@abrophy Heck yeah! React here we come! I'll finish up a few things on this branch so that we have a finalized HTML structure / CSS classnames, and then I'll make another branch to convert these changes into React components.

**Comment by abrophy** [comment]
Was unnecessarily concerned about possible conflicts with react, have tested it and it looks to be working

**Comment by nma** [comment]
Mind if I use snippets from this commit in the documentation task on how to use React? :)

Glad to see that the react infrastructure upgrade is seeing use now 👍

**Comment by baohouse** [comment]
@nma Oh, it's far from done, but yeah, it'd be good to document a primer on how to build a React component and embed it into the ERB.

**Comment by timofonic** [comment]
@julianguyen @nma @baohouse @abrophy Any news about this?

**Comment by baohouse** [comment]
@timofonic #691 Looks like we'll want to focus on that; this PR here is minor and will be obsolete by #691.

**Pull request closed without merging**
