### PR TITLE
Added hyperlinks - Fixes issue [#799]

### PR DESCRIPTION
**Pull request by f3mshep**
Pull request fixes [issue #799](https://github.com/ifmeorg/ifme/issues/799).

All bold text with a corresponding function path is now a hyperlink.

- Added singular of categories to every locale.yml except for italian
- Updated faq view to interpolate links into the locale .yml file
- Group view used resources from the faq section on the locale .yml files, updated Group view to also
interpolate links

screenshot from 2018-02-13 14-17-33

### CODE REVIEW

**Comment by f3mshep** [comment]
According to the test suite, nokogiri has security vulnerability. Is there something I can do to fix that?

**Comment by f3mshep** [comment]
Heh I just needed to run bundler update to update nokogiri, fingers crossed!!

**Comment by julianguyen** [comment]
Just recently merged a fix for Nokogiri by @tmoore! Can you try rebasing?

**Comment by andy5995** [comment]
Only problem here is the merge conflict

```
<<<<<<< added_hyperlinks
    nio4r (2.2.0)
=======
    nio4r (2.1.0)
>>>>>>> master
```

Which version would you like?

**Comment by julianguyen** [comment]
Re @andy5995 comment: you should choose the most recent version of that gem! Thanks for the call out Andy!

**Comment by andy5995** [comment]
@julianguyen had approved this, but later it suffered from merge conflict. I resolved that, but this patch is now failing circle ci tests.

**Comment by baohouse** [comment]
@f3mshep Feel free to merge!

**Comment by andy5995** [comment]
After I rebased (using the `update branch` button), the Circle code integration test failed:

https://circleci.com/gh/ifmeorg/ifme/2401?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

which means the approving review is now null and void :(

**Comment by baohouse** [comment]
@andy5995 Looks like Vietnamese language support wasn't in this branch at the time @f3mshep worked on it. Now that Vietnamese language is there, we'll need to update the appropriate Vietnamese language files with the missing entries.

**Comment by aSquare14** [comment]
@julianguyen  @f3mshep  Could me and Prateksha finish this up ? We are almost done wth reporting feature and were looking to finish up other stuff

**Comment by aSquare14** [comment]
@f3mshep  Thanks for working on this. I am finishing it up :) Amazing work :heart:

**Pull request closed without merging**
