### PR TITLE
100% Translated file for devise.fl.yml File

### PR DESCRIPTION
**Pull request by vinzruzell**
Hi. This is my completed Filipino Translation for devise.en.yml file into devise.fl.yml file.

### CODE REVIEW

**Comment by vinzruzell** [comment]
Ohh...im sorry for that..i will send another pull request. Thank you for
the information.

**Comment by vinzruzell** [comment]
HI. I have updated my translation. I would like to ask why failed on checks? thank you :)

**Comment by vinzruzell** [comment]
Hi @julianguyen can I ask what is the problem of this>?

**Comment by cartothemax** [comment]
Hey @vinzruzell looks like you have some failing tests is the problem.  

Here is a link in the Wiki for information regarding how to get the tests related to translations to pass https://github.com/ifmeorg/ifme/wiki/Translations#testing

You will need to add your new `devise.fil.yml` as an entry to the `LOCALES_OBJECT` in this file [`compare_locales_support.rb`](https://github.com/ifmeorg/ifme/blob/master/spec/support/compare_locales_support.rb)

After `devise_filipino` I would add an entry like this `devise_filipino: "#{LOCALES_DIR}/devise.fil.yml"

Then within `spec/compare_locales_support_spec.rb` you will need to add a test like this:
```
context 'when comparing to devise_filipino' do
  subject { described_class.compare(source, :devise_filipino) }
  it { is_expected.to be_empty }
end
```

Here is another pull requests that is adding Dutch to the site that could be a useful reference as well! https://github.com/ifmeorg/ifme/pull/714/files

Feel free to ask any other questions you may have.  Thanks!

**Pull request closed without merging**
